name: Build and Deploy Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Install hugo
        run: sudo apt install -y hugo

      - name: Build website
        run: hugo --gc --minify

      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.event_name == 'push'
        with:
          clean: true
          clean-exclude: |
            docs
          branch: gh-pages
          folder: public
